FROM jenkins/jenkins:lts

USER root

# Docker CLI 설치 (Debian/Ubuntu 기준)
RUN apt-get update && apt-get install -y docker.io

# docker-compose 설치 (v1 기준)
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/bin/docker-compose && \
  chmod +x /usr/local/bin/docker-compose

# docker 그룹 권한 조정 + jenkins 유저 그룹 추가
RUN groupmod -g 988 docker
RUN usermod -aG docker jenkins

USER jenkins